# Generated by Django 4.1.5 on 2023-03-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='createt_at',
            new_name='created_at',
        ),
    ]
